[package]
name = "impl-2048"
version = "0.1.0"
authors = ["Arnaud Paré-Vogt <arnaud.parevogt@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tfe = "0.1"
